### ISSUE TITLE
Adding tags to theme

### ISSUE THREAD

**Issue by nikdata** [road2stat/hugo-tanka#2]
I've been trying to figure out how to add tags & categories to the content pages. I found the following site that helped me add the necessary code:

https://www.jakewiesler.com/blog/hugo-taxonomies/

Following that tutorial, I added the necessary files. I edited the single.html file (found in hugo-tanka/layouts/_default/).

The end result is that I can see tags listed for content that was created in a markdown format: https://nik.netlify.com/post/hello-markdown/

However, I cannot see tags listed for content that was created using RMarkdown: https://nik.netlify.com/post/magic-8-ball-function/

What's ironic is that when I do a blogdown::serve_site() on RStudio, I can see the tags listed for the content created through RMarkdown:

<img width="394" alt="Screen Shot 2019-05-27 at 7 09 51 AM" src="https://user-images.githubusercontent.com/24734983/58418822-85141100-804e-11e9-83e1-ef47aff302cf.png">

Any suggestions/tips on what I may need to edit or what I'm doing wrong?

Reference:
- My GitHub repo where my posts are: https://github.com/nikdata/blognik

**Comment by nikdata** [comment]
So the tag appears as long as I don't "build" the website in RStudio. Here are the steps I took to get the tags to show up on a post in RMarkdown (.Rmd extension):

1. Add content
2. add tags
3. knit
4. commit & push to GitHub
5. wait for Netlify to deploy
6. Success

If however, I click on the "build" icon in RStudio (equivalent I think to `blogdown::build_site()`), and then I commit & push to GitHub, the published post will not have the tags listed.

**Comment by nanxstats** [comment]
@nikdata -not sure what's the real issue (maybe the local Hugo version and Netlify's version are different?), but in case it's helpful for debugging, hugo-renga supports displaying tags in posts and the dedicated tags page: https://github.com/nanxstats/hugo-renga so you could probably borrow the code there and see if it works.
